name: CV Updater

on: push

jobs:
  cv-update:
    name: Update cv
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2      
      - name: Recompile and save CV
        uses: ./
